### ISSUE TITLE
Flex-layout fxFlex functionality not fully supported

### ISSUE THREAD

**Issue by lievenjanssen** [philmtd/css-fx-layout#11]
I think if we could support flex-basis aliases and some column/row layouting options we could come a long way.

Possible data attribute implementation for flex-basis aliases:
```scss
*[data-fx-flex^="grow"] {
    flex: 1 1 100%;
}

*[data-fx-flex^="initial"] {
    flex: 0 1 auto;
}

*[data-fx-flex^="auto"] {
    flex-basis: auto;
}

*[data-fx-flex^="none"] {
    flex: 0 0 auto;
}

*[data-fx-flex^="nogrow"] {
    flex: 0 1 auto;
}

*[data-fx-flex^="noshrink"] {
    flex: 1 0 auto;
}
```

Possible data attribute implementation for column/row layouting (support for 5 ,10, ..., 95):
```scss
@for $i from 1 through 20 {
    *[data-fx-flex^="#{$i * 5}"] {
        flex: 1 1 $i * 5%;
    }
}
```
